
version: 0.2
phases:
 install:
   commands:
     - echo Installing composer dependencies...
     - composer install
     - echo Installing npm packages...
     - npm install

 build:
   commands:
     - echo Build started on `date`
     - npm run prod

 post_build:
   commands:
     - echo Build completed on `date`
